version: "3.8"
services:
    web:
        container_name: web
        restart: always
        build: .
        ports: 
            - "4000:3000"
        links: 
            - "mongo"
        volumes: .:/usr/src/app

    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27018:27017"
        logging:
            driver: none
